# Generated by Django 5.0 on 2024-01-09 02:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_service', 'In Service'), ('awaiting_parts', 'In Service - Awaiting Parts'), ('out_of_service', 'Out of Service')], default='in_service', max_length=20)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.machinemaster')),
            ],
        ),
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troubleshooting_and_repair', models.TextField()),
                ('time_spent', models.IntegerField()),
                ('repair_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorder.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='PartRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('comments', models.CharField(max_length=255)),
                ('part_required', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorder.workorder')),
            ],
        ),
    ]
