# Generated by Django 5.0.1 on 2024-07-09 06:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_status', models.CharField(choices=[('IN SERVICE', 'IN SERVICE'), ('OUT OF SERVICE', 'OUT OF SERVICE')], default='IN SERVICE', max_length=60)),
                ('maintenance_ticket', models.CharField(choices=[('TROUBLESHOOTING', 'TROUBLESHOOTING'), ('AWAITNG PARTS', 'AWAITNG PARTS'), ('NEEDS MEM CLEAR', 'NEEDS MEM CLEAR'), ('MONITORING', 'MONITORING'), ('REPAIRED', 'REPAIRED')], default='TROUBLESHOOTING', max_length=60)),
                ('status', models.CharField(choices=[('TROUBLESHOOTING', 'TROUBLESHOOTING'), ('AWAITNG PARTS', 'AWAITNG PARTS'), ('NEEDS MEM CLEAR', 'NEEDS MEM CLEAR'), ('MONITORING', 'MONITORING'), ('REPAIRED', 'REPAIRED')], default='Troubleshooting', max_length=60)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('current_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostics', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('asset_number', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('central_office_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('slot_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.slotmachine')),
            ],
        ),
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('diagnostics', models.TextField(blank=True, null=True)),
                ('reason_for_repair', models.TextField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.today)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('user_stamp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repair_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorder.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='PartsRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(max_length=255)),
                ('price_extension', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('work_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorder.workorder')),
            ],
        ),
    ]
