# Generated by Django 5.0.1 on 2024-02-11 18:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MACHINE TROUBLESHOOTING', 'TROUBLESHOOTING'), ('MACHINE DOWN - AWAITNG PARTS', 'MACHINE DOWN - AWAITNG PARTS'), ('MACHINE IN SERVICE - AWAITNG PARTS', 'MACHINE IN SERVICE - AWAITNG PARTS'), ('REPAIR COMPLETED', 'REPAIR COMPLETED')], default='Troubleshooting', max_length=60)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('reason_for_repair', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostics', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('asset_number', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.egm')),
            ],
        ),
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('diagnostics', models.TextField(blank=True, null=True)),
                ('reason_for_repair', models.TextField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.today)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('user_stamp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repair_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorder.workorder')),
            ],
        ),
    ]
