# Generated by Django 5.0 on 2024-01-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='image_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
