# Generated by Django 5.0 on 2024-01-09 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequired',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
    ]
