# Generated by Django 5.0.1 on 2024-03-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_partsrequired'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='central_office_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
