# Generated by Django 5.0 on 2024-01-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_repairlog_image_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='image_key',
        ),
    ]
