# Generated by Django 5.0.1 on 2024-06-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0004_rename_reason_for_repair_workorder_current_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='maintenance_ticket',
            field=models.CharField(choices=[('TROUBLESHOOTING', 'TROUBLESHOOTING'), ('AWAITNG PARTS', 'AWAITNG PARTS'), ('REPAIR COMPLETED', 'REPAIR COMPLETED')], default='TROUBLESHOOTING', max_length=60),
        ),
        migrations.AddField(
            model_name='workorder',
            name='service_status',
            field=models.CharField(choices=[('IN SERVICE', 'IN SERVICE'), ('OUT OF SERVICE', 'OUT OF SERVICE')], default='IN SERVICE', max_length=60),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('TROUBLESHOOTING', 'TROUBLESHOOTING'), ('AWAITNG PARTS', 'AWAITNG PARTS'), ('REPAIR COMPLETED', 'REPAIR COMPLETED')], default='Troubleshooting', max_length=60),
        ),
    ]
