# Generated by Django 5.0.1 on 2024-06-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0005_workorder_maintenance_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='maintenance_ticket',
            field=models.CharField(choices=[('TROUBLESHOOTING', 'TROUBLESHOOTING'), ('AWAITNG PARTS', 'AWAITNG PARTS'), ('REPAIR COMPLETED', 'REPAIR COMPLETED')], default='REPAIR COMPLETED', max_length=60),
        ),
    ]
