# Generated by Django 5.0 on 2024-01-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('workorder', '0005_alter_repairlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='machine',
        ),
        migrations.AddField(
            model_name='workorder',
            name='machine',
            field=models.ManyToManyField(to='assets.machinemaster'),
        ),
    ]
