# Generated by Django 5.0 on 2024-02-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0006_remove_repairlog_image_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='asset_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='game_theme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
