# Generated by Django 5.0 on 2024-01-11 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('workorder', '0006_workorder_title_remove_workorder_machine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='machine',
        ),
        migrations.AddField(
            model_name='workorder',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.machinemaster'),
        ),
    ]
