# Generated by Django 5.0 on 2024-02-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0007_workorder_asset_number_workorder_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='bank',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='game_theme',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='serial_number',
        ),
    ]
