# Generated by Django 5.0 on 2024-02-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0008_rename_bank_workorder_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='recent_update',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
