# Generated by Django 5.0.1 on 2024-06-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0008_alter_workorder_maintenance_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='machine',
        ),
    ]
