# Generated by Django 5.0 on 2024-01-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0008_remove_repairlog_time_spent_alter_workorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='user_stamp',
            new_name='created_by',
        ),
    ]
