# Generated by Django 5.0.1 on 2024-06-11 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_egm_maintenance_ticket'),
        ('workorder', '0009_remove_workorder_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.egm'),
        ),
    ]
