# Generated by Django 5.0 on 2024-01-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0010_delete_partrequired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='title',
        ),
        migrations.AddField(
            model_name='workorder',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='reason_for_repair',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='type_of_repair',
            field=models.CharField(blank=True, choices=[('Player Interface Repairs', 'Player Interface Repairs'), ('Bill Validator Repairs', 'Bill Validator Repairs'), ('Ticket Printer Repairs', 'Ticket Printer Repairs'), ('Card Reader Repairs', 'Card Reader Repairs'), ('Electrical Component Repairs', 'Electrical Component Repairs'), ('Display/Mechanical Reel Repairs', 'Display/Mechanical Reel Repairs'), ('Software Troubleshooting', 'Software Troubleshooting'), ('Sound System Repairs', 'Sound System Repairs'), ('Cabinet Repairs', 'Cabinet Repairs'), ('Network and Communication Repairs', 'Network and Communication Repairs'), ('Power Supply Repairs', 'Power Supply Repairs'), ('Cabinet Lighting Repairs', 'Cabinet Lighting Repairs'), ('Internal Cleaning and Dust Removal', 'Internal Cleaning and Dust Removal'), ('Firmware Updates', 'Firmware Updates'), ('Motherboard Repairs', 'Motherboard Repairs'), ('Backplane Repairs', 'Backplane Repairs')], max_length=60, null=True),
        ),
    ]
