# Generated by Django 5.0 on 2024-01-17 01:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0019_remove_workorder_diagnostics'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='diagnostics',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='reason_for_repair',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
