# Generated by Django 5.0 on 2024-01-17 02:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0023_alter_repairlog_reason_for_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='diagnostics',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10, null=True),
        ),
    ]
