# Generated by Django 5.0 on 2024-01-17 02:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0025_alter_workorder_reason_for_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='diagnostics',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='reason_for_repair',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
