# Generated by Django 5.0 on 2024-01-17 03:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0026_alter_workorder_diagnostics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='diagnostics',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
    ]
