# Generated by Django 5.0 on 2024-01-18 01:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0028_repairlog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='diagnostics',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
    ]
