# Generated by Django 5.1.2 on 2024-12-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_game_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinetest',
            name='machine',
        ),
    ]
