# Generated by Django 5.1.2 on 2024-11-26 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game_test', '0001_initial'),
        ('slot_machines', '0002_rename_slotmachine_egmslotmachine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetest',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='The slot machine associated with this test', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_tests', to='slot_machines.egmslotmachine'),
        ),
    ]
