# Generated by Django 5.0.1 on 2024-02-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vendor', models.CharField(choices=[('Konami', 'Konami'), ('IGT', 'IGT'), ('Bally', 'Bally'), ('WMS', 'WMS'), ('Ainsworth', 'Ainsworth'), ('Aristocrat', 'Aristocrat'), ('Sci Games', 'Sci Games'), ('Everi', 'Everi'), ('Spielo', 'Spielo'), ('AGS', 'AGS'), ('Aruze', 'Aruze'), ('LnW', 'LnW'), ('Incredible Technologies', 'Incredible Technologies')], max_length=50)),
                ('machine_move_risk', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('cabinet_type', models.CharField(choices=[('Slant Video', 'Slant Video'), ('Upright Video', 'Upright Video')], max_length=20)),
                ('current_amps', models.FloatField()),
            ],
        ),
    ]
