# Generated by Django 5.1.2 on 2024-10-27 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTracker',
            fields=[
                ('machine_serial_number', models.CharField(default='TEMP_SERIAL', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('model_type', models.CharField(blank=True, max_length=255, null=True)),
                ('machine_move_risk', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True)),
                ('current_amps', models.FloatField(blank=True, null=True)),
                ('model_image', models.ImageField(blank=True, null=True, upload_to='model_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='SlotMachine',
            fields=[
                ('casino_id', models.CharField(max_length=100)),
                ('slot_machine_name', models.CharField(max_length=100)),
                ('slot_location', models.CharField(max_length=100)),
                ('slot_cabinet_name', models.CharField(max_length=100)),
                ('textbox34', models.CharField(max_length=100)),
                ('machine_serial_number', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('slot_game_name', models.CharField(max_length=100)),
                ('machine_model_name', models.CharField(max_length=100)),
                ('machine_manufacturer_name1', models.CharField(default='Unknown Manufacturer', max_length=100)),
                ('slot_denomination', models.CharField(max_length=100)),
                ('slot_denomination_value', models.CharField(max_length=100)),
                ('textbox46', models.CharField(max_length=100)),
                ('gaming_day_count', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default='offline', max_length=10)),
            ],
        ),
    ]
