# Generated by Django 5.0 on 2024-01-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemaster',
            name='bank',
            field=models.CharField(default='Default Bank', max_length=255),
        ),
    ]
