# Generated by Django 5.1.2 on 2024-10-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Slot Machine Model', 'verbose_name_plural': 'Slot Machine Models'},
        ),
        migrations.AddField(
            model_name='model',
            name='depreciated_since',
            field=models.DateField(blank=True, help_text='Date when the model was marked as depreciated', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='dimensions',
            field=models.JSONField(blank=True, help_text="Cabinet dimensions as {'height': , 'width': , 'depth': }", null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='is_depreciated',
            field=models.BooleanField(default=False, help_text='Indicates if the model is depreciated'),
        ),
        migrations.AddField(
            model_name='model',
            name='screen_size',
            field=models.FloatField(blank=True, help_text='Screen size in inches', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight of the machine in kg or lb', null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='current_amps',
            field=models.FloatField(blank=True, help_text='Current (in amps) required by the machine', null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='machine_move_risk',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='Risk associated with moving this machine', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_image',
            field=models.ImageField(blank=True, help_text='Image of the model', null=True, upload_to='model_pics/'),
        ),
    ]
