# Generated by Django 5.0 on 2024-02-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egm',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='egm',
            name='game_theme',
        ),
        migrations.RemoveField(
            model_name='egm',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='egm',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='egm',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='egm',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egm',
            name='asset_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
