# Generated by Django 5.0 on 2024-01-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Out of Service', 'Out of Service'), ('In Service, Awaiting Repair', 'In Service, Awaiting Repair')], default='In Service', max_length=50),
        ),
    ]
