# Generated by Django 5.1.2 on 2024-10-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_model_options_model_depreciated_since_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight of the machine in lb', null=True),
        ),
        migrations.AlterField(
            model_name='slotmachine',
            name='machine_model_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.model'),
        ),
    ]
