# Generated by Django 5.0 on 2024-01-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_machinemaster_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemaster',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
