# Generated by Django 5.0.1 on 2024-06-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_egm_maintenance_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egm',
            name='maintenance_ticket',
        ),
    ]
