# Generated by Django 5.1.2 on 2024-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assettracker_slot_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettracker',
            name='machine_model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
