# Generated by Django 5.1.2 on 2024-10-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assettracker_machine_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettracker',
            name='casino_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
