# Generated by Django 5.1.2 on 2024-10-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assettracker_casino_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettracker',
            name='preventative_maintenance_date',
            field=models.DateField(blank=True, help_text='Date of the last preventative maintenance', null=True),
        ),
    ]
