# Generated by Django 5.1.2 on 2024-12-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('casino_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('casino_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='casino_logos/')),
            ],
        ),
    ]
