# Generated by Django 5.1.2 on 2024-11-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='casino_location',
        ),
    ]
