# Generated by Django 5.1.2 on 2024-11-25 02:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalAsset',
            fields=[
                ('machine_name', models.CharField(max_length=100)),
                ('machine_serial_number', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('machine_manufacturer_name1', models.CharField(default='Unknown Manufacturer', max_length=100)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default='offline', max_length=10)),
                ('casino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departmental_assets', to='casinos.casino')),
            ],
        ),
    ]
