# Generated by Django 5.1.2 on 2024-11-25 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmental_assets', '0001_initial'),
        ('machine_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentalasset',
            name='machine_model_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine_models.machinemodel'),
        ),
    ]
