# Generated by Django 5.1.2 on 2024-12-23 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casinos', '0001_initial'),
        ('machine_models', '0001_initial'),
        ('slot_importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressive_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BankedProgressive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressive_name', models.CharField(max_length=100)),
                ('casino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banked_progressive', to='casinos.casino')),
                ('machine_model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banked_progressive', to='machine_models.machinemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BankedLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_level', models.DecimalField(decimal_places=2, help_text='Initial seed amount for the level', max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=1e+16, help_text='Overflow amount exceeding the max level', max_digits=20)),
                ('progressive_increment_percent', models.DecimalField(decimal_places=2, help_text='Increment percentage for the progressive', max_digits=5)),
                ('current_amount', models.DecimalField(decimal_places=2, help_text='Current amount of the level', max_digits=10)),
                ('overflow_amount', models.DecimalField(decimal_places=2, help_text='Overflow amount exceeding the max level', max_digits=10)),
                ('banked_progressive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banked_levels', to='progressive.bankedprogressive')),
            ],
        ),
        migrations.CreateModel(
            name='BEPSLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_level', models.DecimalField(decimal_places=2, help_text='Initial seed amount for the level', max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=1e+16, help_text='Overflow amount exceeding the max level', max_digits=20)),
                ('progressive_increment_percent', models.DecimalField(decimal_places=2, help_text='Increment percentage for the progressive', max_digits=5)),
                ('current_amount', models.DecimalField(decimal_places=2, help_text='Current amount of the level', max_digits=10)),
                ('overflow_amount', models.DecimalField(decimal_places=2, help_text='Overflow amount exceeding the max level', max_digits=10)),
                ('beps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beps_levels', to='progressive.beps')),
            ],
        ),
        migrations.CreateModel(
            name='StandAloneLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressive_pool', models.CharField(blank=True, help_text='Identifier for the progressive pool, e.g., denomination or game theme', max_length=100, null=True)),
                ('seed_level', models.DecimalField(decimal_places=2, help_text='Initial seed amount for the level', max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=1e+16, help_text='Overflow amount exceeding the max level', max_digits=20)),
                ('progressive_increment_percent', models.DecimalField(decimal_places=2, help_text='Increment percentage for the progressive', max_digits=5)),
                ('current_amount', models.DecimalField(decimal_places=2, help_text='Current amount of the level', max_digits=10)),
                ('overflow_amount', models.DecimalField(decimal_places=2, help_text='Overflow amount exceeding the max level', max_digits=10)),
                ('stand_alone_progressive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_alone_levels', to='slot_importer.slotmachine')),
            ],
        ),
    ]
