# Generated by Django 5.1.2 on 2024-12-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankedlevel',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=99999999.0, help_text='Overflow amount exceeding the max level', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bepslevel',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=99999999.0, help_text='Overflow amount exceeding the max level', max_digits=10),
        ),
        migrations.AlterField(
            model_name='standalonelevel',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=99999999.0, help_text='Overflow amount exceeding the max level', max_digits=10),
        ),
    ]
