# Generated by Django 5.1.2 on 2024-12-23 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressive', '0002_alter_bankedlevel_max_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progressive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressive_name', models.CharField(max_length=255)),
                ('progressive_type', models.CharField(choices=[('BANKED', 'Banked Progressive'), ('BEPS', 'BEPS Progressive'), ('STANDALONE', 'Standalone Progressive')], max_length=50)),
                ('banked_progressive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progressive_banked', to='progressive.bankedprogressive')),
                ('beps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progressive_banked', to='progressive.beps')),
            ],
        ),
        migrations.AlterField(
            model_name='standalonelevel',
            name='stand_alone_progressive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_alone_levels', to='progressive.progressive'),
        ),
    ]
