# Generated by Django 5.1.2 on 2024-10-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='price',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per individual part', max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
    ]
