# Generated by Django 5.0 on 2024-01-14 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('workorder', '0010_delete_partrequired'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('comments', models.CharField(max_length=255)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('part_required', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorder.workorder')),
            ],
        ),
    ]
