# Generated by Django 5.0.1 on 2024-03-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartsOrder',
            new_name='PartsRequired',
        ),
    ]
