# Generated by Django 5.0 on 2024-01-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_partrequired'),
        ('workorder', '0010_delete_partrequired'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartRequired',
            new_name='PartsOrder',
        ),
    ]
