# Generated by Django 5.0.1 on 2024-03-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_partsorder_partsrequired'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartsRequired',
        ),
    ]
