# Generated by Django 5.0 on 2024-01-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_partrequired_partsorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partsorder',
            old_name='comments',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='partsorder',
            old_name='part_required',
            new_name='work_order',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quatity_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
