# Generated by Django 5.0.1 on 2024-03-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_partsrequired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quatity_available',
        ),
    ]
