# Generated by Django 5.0 on 2024-01-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_comments_partsorder_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsorder',
            name='price_extension',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
