# Generated by Django 5.0.1 on 2024-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_purchaseorder_purchaseorderitem_purchaseorder_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
