# Generated by Django 5.1.2 on 2024-11-26 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('slot_machines', '0002_rename_slotmachine_egmslotmachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotmachinemaintenanceform',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slot_machines.egmslotmachine'),
        ),
    ]
