# Generated by Django 5.1.2 on 2024-12-03 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kobetron',
            name='security_user',
            field=models.ForeignKey(blank=True, help_text='Security user who performed the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kobetron_security_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logicseals',
            name='initial_seal_verified_by',
            field=models.ForeignKey(blank=True, help_text='Security user who verified the initial seal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_seal_verified_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logicseals',
            name='new_seal_verified_by',
            field=models.ForeignKey(blank=True, help_text='Security user who verified the new seal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_seal_verified_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
