# Generated by Django 5.1.2 on 2024-10-28 00:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_purchaseorderitem_purchase_order_and_more'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.CreateModel(
            name='PartsRequested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled')], default='PENDING', max_length=20)),
                ('maintenance_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_requested', to='maintenance.slotmachinemaintenanceform')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='PartsUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('maintenance_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='maintenance.slotmachinemaintenanceform')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
    ]
