# Generated by Django 5.1.2 on 2024-12-03 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_kobetron_security_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logicseals',
            name='seal_removed_date',
            field=models.DateTimeField(blank=True, help_text='Date when the initial seal was removed by the technician.', null=True),
        ),
        migrations.AddField(
            model_name='logicseals',
            name='technician_removed',
            field=models.ForeignKey(blank=True, help_text='Technician who removed the initial seal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians_removed_seals', to=settings.AUTH_USER_MODEL),
        ),
    ]
