# Generated by Django 5.1.2 on 2024-12-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_rename_narrative_troubleshootinglog_repair_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleshootinglog',
            name='troubleshooting_photo',
            field=models.ImageField(blank=True, help_text='Upload a photo related to the troubleshooting', null=True, upload_to='troubleshooting_photos/'),
        ),
    ]
