# Generated by Django 5.1.2 on 2024-10-28 02:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_purchaseorderitem_purchase_order_and_more'),
        ('maintenance', '0002_remove_task_assigned_to_partsrequested_partsused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsused',
            name='maintenance_form',
        ),
        migrations.RemoveField(
            model_name='partsused',
            name='part',
        ),
        migrations.CreateModel(
            name='PartRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the part was requested')),
                ('date_fulfilled', models.DateTimeField(blank=True, help_text='Date when the part request was fulfilled', null=True)),
                ('status', models.CharField(choices=[('SITE_REQ', 'Site Requested'), ('CO_IN_STOCK', 'CO In Stock'), ('CO_SENT', 'CO Sent'), ('CO_ORDERED', 'CO Ordered'), ('PART_ORDERED', 'Partial Order'), ('FULFILLED', 'Fulfilled')], default='PENDING', max_length=20)),
                ('maintenance_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_required', to='maintenance.slotmachinemaintenanceform')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
        migrations.DeleteModel(
            name='PartsRequested',
        ),
        migrations.DeleteModel(
            name='PartsUsed',
        ),
    ]
