# Generated by Django 5.1.2 on 2024-12-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_troubleshootinglog_troubleshooting_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotmachinemaintenanceform',
            old_name='issue_description',
            new_name='first_observations',
        ),
    ]
