# Generated by Django 5.1.2 on 2024-10-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_remove_partsused_maintenance_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequired',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SITE_REQ', 'Site Requested'), ('CO_IN_STOCK', 'CO In Stock'), ('CO_SENT', 'CO Sent'), ('CO_ORDERED', 'CO Ordered'), ('FULFILLED', 'Fulfilled')], default='PENDING', max_length=20),
        ),
    ]
