# Generated by Django 5.1.2 on 2024-12-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_rename_issue_description_slotmachinemaintenanceform_first_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotmachinemaintenanceform',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image related to the maintenance', null=True, upload_to='maintenance_images/'),
        ),
    ]
