# Generated by Django 5.1.2 on 2025-01-06 04:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_slotmachinemaintenanceform_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=255)),
                ('part_description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='part_pictures/')),
                ('quote_number', models.CharField(blank=True, help_text='Quote number associated with the request', max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('CO_ORDERED', 'CO Ordered'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('INSTALLED', 'Installed')], default='PENDING', max_length=20)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_ordered', models.DateTimeField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('date_installed', models.DateTimeField(blank=True, null=True)),
                ('maintenance_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts_required', to='maintenance.slotmachinemaintenanceform')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_parts_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
