# Generated by Django 5.1.2 on 2024-10-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_partrequired_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequired',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per individual part', max_digits=10, null=True),
        ),
    ]
