# Generated by Django 5.1.2 on 2024-11-03 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_partrequired_price_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoTestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='casino_test_record', to='maintenance.slotmachinemaintenanceform')),
            ],
        ),
        migrations.CreateModel(
            name='BetWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('won', models.DecimalField(decimal_places=2, max_digits=10)),
                ('casino_test_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_win', to='maintenance.casinotestrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Progressive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_values', models.JSONField()),
                ('after_values', models.JSONField()),
                ('casino_test_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressive', to='maintenance.casinotestrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SoftGMU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_cashable_promo_in', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cashable_promo_in', models.DecimalField(decimal_places=2, max_digits=10)),
                ('non_cashable_promo_out', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coin_in_bets', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coin_out_wins', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jackpot_handpaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_ticket_in', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_ticket_out', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fives', models.IntegerField()),
                ('tens', models.IntegerField()),
                ('twenties', models.IntegerField()),
                ('fifties', models.IntegerField()),
                ('hundreds', models.IntegerField()),
                ('player_tracking_before', models.IntegerField()),
                ('player_tracking_after', models.IntegerField()),
                ('casino_test_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_gmu', to='maintenance.casinotestrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('points', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('denom_5', models.BooleanField(default=False)),
                ('denom_10', models.BooleanField(default=False)),
                ('denom_20', models.BooleanField(default=False)),
                ('denom_50', models.BooleanField(default=False)),
                ('denom_100', models.BooleanField(default=False)),
                ('solution_clear', models.TextField(blank=True, null=True)),
                ('casino_test_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_settings', to='maintenance.casinotestrecord')),
            ],
        ),
    ]
