# Generated by Django 5.1.2 on 2024-11-04 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_casinotestrecord_betwin_progressive_softgmu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kobetron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rom_position', models.CharField(help_text='Position of the ROM', max_length=50)),
                ('program_number', models.CharField(help_text='Program number of the ROM', max_length=50)),
                ('mfg_date', models.DateField(help_text='Manufacturing date of the ROM')),
                ('kobetron_number', models.CharField(help_text='Kobetron number', max_length=50)),
                ('security_reviewed', models.BooleanField(default=False, help_text='Indicates whether security has reviewed and approved this record')),
                ('security_review_date', models.DateTimeField(blank=True, help_text='Date when security reviewed the record', null=True)),
                ('slot_machine_maintenance_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kobetron_records', to='maintenance.slotmachinemaintenanceform')),
                ('technician_signature', models.ForeignKey(blank=True, help_text='Technician who signed off', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
