# Generated by Django 5.1.2 on 2024-11-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_kobetron'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kobetron',
            old_name='kobetron_number',
            new_name='kobetron_signature',
        ),
    ]
