# Generated by Django 5.1.2 on 2024-11-04 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_rename_kobetron_number_kobetron_kobetron_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinotestrecord',
            name='maintenance_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino_test_record', to='maintenance.slotmachinemaintenanceform'),
        ),
    ]
