# Generated by Django 5.1.2 on 2024-11-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_alter_casinotestrecord_maintenance_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsettings',
            name='solution_clear',
        ),
        migrations.AddField(
            model_name='casinotestrecord',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
