# Generated by Django 5.1.2 on 2024-11-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_remove_testsettings_solution_clear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressive',
            name='after_values',
        ),
        migrations.RemoveField(
            model_name='progressive',
            name='before_values',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='cash_ticket_in',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='cash_ticket_out',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='cashable_promo_in',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='coin_in_bets',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='coin_out_wins',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='fifties',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='fives',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='hundreds',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='jackpot_handpaid',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='non_cashable_promo_in',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='non_cashable_promo_out',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='tens',
        ),
        migrations.RemoveField(
            model_name='softgmu',
            name='twenties',
        ),
        migrations.AddField(
            model_name='progressive',
            name='after_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dollar amount after maintenance.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='progressive',
            name='before_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dollar amount before maintenance.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='cash_ticket_in_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='After value of cash ticket in', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='cash_ticket_in_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Before value of cash ticket in', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='cash_ticket_out_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='After value of cash ticket out', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='cash_ticket_out_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Before value of cash ticket out', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='cashable_promo_in_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='After value of cashable promo in', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='cashable_promo_in_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Before value of cashable promo in', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='coin_in_bets_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='After value of coin-in bets', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='coin_in_bets_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Before value of coin-in bets', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='coin_out_wins_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='After value of coin-out wins', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='coin_out_wins_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Before value of coin-out wins', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='fifties_after',
            field=models.IntegerField(blank=True, help_text='After value for $50 bills', null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='fifties_before',
            field=models.IntegerField(blank=True, help_text='Before value for $50 bills', null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='fives_after',
            field=models.IntegerField(blank=True, help_text='After value for $5 bills', null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='fives_before',
            field=models.IntegerField(blank=True, help_text='Before value for $5 bills', null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='hundreds_after',
            field=models.IntegerField(blank=True, help_text='After value for $100 bills', null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='hundreds_before',
            field=models.IntegerField(blank=True, help_text='Before value for $100 bills', null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='jackpot_handpaid_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='After value of jackpot handpaid', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='jackpot_handpaid_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Before value of jackpot handpaid', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='non_cashable_promo_in_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='After value of non-cashable promo in', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='non_cashable_promo_in_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Before value of non-cashable promo in', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='non_cashable_promo_out_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='After value of non-cashable promo out', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='non_cashable_promo_out_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Before value of non-cashable promo out', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='tens_after',
            field=models.IntegerField(blank=True, help_text='After value for $10 bills', null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='tens_before',
            field=models.IntegerField(blank=True, help_text='Before value for $10 bills', null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='twenties_after',
            field=models.IntegerField(blank=True, help_text='After value for $20 bills', null=True),
        ),
        migrations.AddField(
            model_name='softgmu',
            name='twenties_before',
            field=models.IntegerField(blank=True, help_text='Before value for $20 bills', null=True),
        ),
        migrations.AlterField(
            model_name='softgmu',
            name='player_tracking_after',
            field=models.IntegerField(blank=True, help_text='Player tracking value after', null=True),
        ),
        migrations.AlterField(
            model_name='softgmu',
            name='player_tracking_before',
            field=models.IntegerField(blank=True, help_text='Player tracking value before', null=True),
        ),
    ]
