# Generated by Django 5.1.2 on 2024-11-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_remove_progressive_after_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressive',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Level of the progressive meter (e.g., 1 for Grand, 2 for Major)', null=True),
        ),
    ]
