# Generated by Django 5.1.2 on 2024-11-04 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_progressive_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftGMUAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_cashable_promo_in', models.DecimalField(blank=True, decimal_places=2, help_text='After value of non-cashable promo in', max_digits=10, null=True)),
                ('cashable_promo_in', models.DecimalField(blank=True, decimal_places=2, help_text='After value of cashable promo in', max_digits=10, null=True)),
                ('non_cashable_promo_out', models.DecimalField(blank=True, decimal_places=2, help_text='After value of non-cashable promo out', max_digits=10, null=True)),
                ('coin_in_bets', models.DecimalField(blank=True, decimal_places=2, help_text='After value of coin-in bets', max_digits=10, null=True)),
                ('coin_out_wins', models.DecimalField(blank=True, decimal_places=2, help_text='After value of coin-out wins', max_digits=10, null=True)),
                ('jackpot_handpaid', models.DecimalField(blank=True, decimal_places=2, help_text='After value of jackpot handpaid', max_digits=10, null=True)),
                ('cash_ticket_in', models.DecimalField(blank=True, decimal_places=2, help_text='After value of cash ticket in', max_digits=10, null=True)),
                ('cash_ticket_out', models.DecimalField(blank=True, decimal_places=2, help_text='After value of cash ticket out', max_digits=10, null=True)),
                ('fives', models.IntegerField(blank=True, help_text='After value for $5 bills', null=True)),
                ('tens', models.IntegerField(blank=True, help_text='After value for $10 bills', null=True)),
                ('twenties', models.IntegerField(blank=True, help_text='After value for $20 bills', null=True)),
                ('fifties', models.IntegerField(blank=True, help_text='After value for $50 bills', null=True)),
                ('hundreds', models.IntegerField(blank=True, help_text='After value for $100 bills', null=True)),
                ('player_tracking', models.IntegerField(blank=True, help_text='Player tracking value after', null=True)),
                ('casino_test_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soft_gmu_after', to='maintenance.casinotestrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SoftGMUBefore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_cashable_promo_in', models.DecimalField(blank=True, decimal_places=2, help_text='Before value of non-cashable promo in', max_digits=10, null=True)),
                ('cashable_promo_in', models.DecimalField(blank=True, decimal_places=2, help_text='Before value of cashable promo in', max_digits=10, null=True)),
                ('non_cashable_promo_out', models.DecimalField(blank=True, decimal_places=2, help_text='Before value of non-cashable promo out', max_digits=10, null=True)),
                ('coin_in_bets', models.DecimalField(blank=True, decimal_places=2, help_text='Before value of coin-in bets', max_digits=10, null=True)),
                ('coin_out_wins', models.DecimalField(blank=True, decimal_places=2, help_text='Before value of coin-out wins', max_digits=10, null=True)),
                ('jackpot_handpaid', models.DecimalField(blank=True, decimal_places=2, help_text='Before value of jackpot handpaid', max_digits=10, null=True)),
                ('cash_ticket_in', models.DecimalField(blank=True, decimal_places=2, help_text='Before value of cash ticket in', max_digits=10, null=True)),
                ('cash_ticket_out', models.DecimalField(blank=True, decimal_places=2, help_text='Before value of cash ticket out', max_digits=10, null=True)),
                ('fives', models.IntegerField(blank=True, help_text='Before value for $5 bills', null=True)),
                ('tens', models.IntegerField(blank=True, help_text='Before value for $10 bills', null=True)),
                ('twenties', models.IntegerField(blank=True, help_text='Before value for $20 bills', null=True)),
                ('fifties', models.IntegerField(blank=True, help_text='Before value for $50 bills', null=True)),
                ('hundreds', models.IntegerField(blank=True, help_text='Before value for $100 bills', null=True)),
                ('player_tracking', models.IntegerField(blank=True, help_text='Player tracking value before', null=True)),
                ('casino_test_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soft_gmu_before', to='maintenance.casinotestrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='SoftGMU',
        ),
    ]
