# Generated by Django 5.1.2 on 2024-11-04 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_softgmuafter_softgmubefore_delete_softgmu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicSeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_seal_serial', models.CharField(blank=True, help_text='Serial number of the initial seal before accessing logic.', max_length=20, null=True)),
                ('initial_seal_verified_by_security', models.BooleanField(default=False, help_text='Has the initial seal been verified by security?')),
                ('initial_seal_verified_date', models.DateTimeField(blank=True, help_text='Date when the initial seal was verified by security.', null=True)),
                ('new_seal_serial', models.CharField(blank=True, help_text='Serial number of the new seal applied after work is completed.', max_length=20, null=True)),
                ('new_seal_verified_by_security', models.BooleanField(default=False, help_text='Has the new seal been verified by security?')),
                ('new_seal_verified_date', models.DateTimeField(blank=True, help_text='Date when the new seal was verified by security.', null=True)),
                ('work_completed_date', models.DateTimeField(blank=True, help_text='Date when the technician completed their work and applied the new seal.', null=True)),
                ('casino_test_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logic_seals', to='maintenance.slotmachinemaintenanceform')),
                ('technician', models.ForeignKey(blank=True, help_text='Technician who applied the new seal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logic_seal_technician', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
