# Generated by Django 5.1.2 on 2024-12-21 05:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casinos', '0001_initial'),
        ('machine_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotMachine',
            fields=[
                ('slot_machine_name', models.CharField(max_length=100)),
                ('slot_location', models.CharField(max_length=100)),
                ('date_purchased', models.DateField(blank=True, help_text='Date when the model was introduced or purchased', null=True)),
                ('machine_serial_number', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('slot_game_name', models.CharField(max_length=100)),
                ('slot_denomination_value', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default='offline', max_length=10)),
                ('casino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_machines_importer', to='casinos.casino')),
                ('machine_model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_machines_importer', to='machine_models.machinemodel')),
            ],
        ),
    ]
