# Generated by Django 5.1.2 on 2024-12-23 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressive', '0001_initial'),
        ('slot_importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotmachine',
            name='banked_progressive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_machines_importer', to='progressive.bankedprogressive'),
        ),
        migrations.AddField(
            model_name='slotmachine',
            name='beps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_machines_importer', to='progressive.beps'),
        ),
    ]
