# Generated by Django 5.1.2 on 2024-11-25 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot_importer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotmachine',
            name='gaming_day_count',
        ),
        migrations.RemoveField(
            model_name='slotmachine',
            name='textbox34',
        ),
        migrations.RemoveField(
            model_name='slotmachine',
            name='textbox46',
        ),
    ]
