# Generated by Django 5.1.2 on 2024-12-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_importer', '0002_slotmachine_banked_progressive_slotmachine_beps'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotmachine',
            name='open_ticket',
            field=models.BooleanField(default=False, help_text='Indicates if there is an open maintenance ticket for the machine'),
        ),
        migrations.AddField(
            model_name='slotmachine',
            name='preventative_maintenance_date',
            field=models.DateField(blank=True, help_text='The date when the last preventative maintenance was performed', null=True),
        ),
    ]
