# Generated by Django 5.1.2 on 2024-11-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotMachine',
            fields=[
                ('machine_serial_number', models.CharField(default='TEMP_SERIAL', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('slot_machine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot_location', models.CharField(blank=True, max_length=100, null=True)),
                ('slot_game_name', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('casino_id', models.CharField(blank=True, max_length=100, null=True)),
                ('preventative_maintenance_date', models.DateField(blank=True, help_text='Date of the last preventative maintenance', null=True)),
            ],
        ),
    ]
