# Generated by Django 5.1.2 on 2024-11-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('slot_machines', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlotMachine',
            new_name='EGMSlotMachine',
        ),
    ]
