# Generated by Django 5.1.2 on 2024-12-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the manufacturer', max_length=255, unique=True)),
                ('website', models.URLField(blank=True, help_text='Official website of the manufacturer', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo or picture of the manufacturer', null=True, upload_to='manufacturer_logos/')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('model_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('model_type', models.CharField(blank=True, max_length=255, null=True)),
                ('machine_move_risk', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='Risk associated with moving this machine', max_length=20, null=True)),
                ('current_amps', models.FloatField(blank=True, help_text='Current (in amps) required by the machine', null=True)),
                ('is_end_of_life', models.BooleanField(default=False, help_text='Indicates if the model is at the end of its life')),
                ('end_of_life_date', models.DateField(blank=True, help_text='Date when the model was marked as end of life', null=True)),
                ('model_image', models.ImageField(blank=True, help_text='Image of the model', null=True, upload_to='model_pics/')),
                ('manufacturer', models.ForeignKey(help_text='Manufacturer of this machine', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_models', to='machine_models.manufacturer')),
            ],
            options={
                'verbose_name': 'Slot Machine Model',
                'verbose_name_plural': 'Slot Machine Models',
            },
        ),
    ]
