# Generated by Django 5.1.2 on 2024-12-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinemodel',
            name='depreciated_since',
        ),
        migrations.RemoveField(
            model_name='machinemodel',
            name='is_depreciated',
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='end_of_life_date',
            field=models.DateField(blank=True, help_text='Date when the model was marked as end of life', null=True),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='is_end_of_life',
            field=models.BooleanField(default=False, help_text='Indicates if the model is at the end of its life'),
        ),
    ]
